DROP TABLE IF EXISTS tb1;
DROP TABLE IF EXISTS tb2;

CREATE TABLE tb1 (
  id SERIAL PRIMARY KEY,
  username VARCHAR NOT NULL,
  password VARCHAR NOT NULL
);

CREATE TABLE tb2 (
  id SERIAL PRIMARY KEY,
  foreign_id INT NOT NULL,
  title VARCHAR NOT NULL,
  body VARCHAR NOT NULL,
  FOREIGN KEY (foreign_id) REFERENCES tb1 (id)
);

COMMIT